name: Build

on:
  push:
    branches:
      - add-ci

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - run: sudo apt install python3-venv python3-dev libtinfo5 libtinfo-dev gcc-multilib g++-multilib
    - run: sudo pip3 install ledgerblue

    - name: Prepare dev-environment
      run: ./prepare-devenv.sh s

    - run: make

    - name: Setup Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Start Speculos
      run: docker-compose up -d

    - name: Wait Speculos
      run: .github/tools/wait-speculos.sh

    - name: Run tests
      run: node test/index.js

    - uses: actions/upload-artifact@v2
      with:
        name: app
        path: bin/app.elf

  release:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v2

      - run: |
          VER="${{ github.ref }}"
          echo "VERSION=${VER#refs/tags/v}" >> $GITHUB_ENV

      - name: Archive Ledger App
        run: zip --junk-paths ledger-app-${{ env.VERSION }}.zip app/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ env.VERSION }}
          files: |
            ledger-app-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

